name: User guide
description: Aimed at day to day users of CiviCRM.
langs:
    en:
        repo: 'https://github.com/civicrm/civicrm-user-guide'
        latest: master
        stable: 4.7
        history:
            - 4.6
    ca:
        repo: 'https://github.com/babu-cat/civicrm-user-guide-ca'
        latest: master
